"""Runtime tuning constants kept out of business logic."""

from __future__ import annotations

FALLBACK_EVENT_LIMIT = 50

LLM_TEMPERATURE = 0.2

PGVECTOR_RECALL_LIMIT = 200
RETRIEVAL_CANDIDATE_MULTIPLIER = 8

FILTER_SCORE_CATEGORY = 3.0
FILTER_SCORE_SKIN_TYPE = 2.0
FILTER_SCORE_BUDGET = 1.0
FILTER_SCORE_SCENARIO = 0.5

RERANK_SCORE_CATEGORY = 3
RERANK_SCORE_SKIN_TYPE = 2
RERANK_SCORE_BUDGET = 1
RERANK_AVOID_PENALTY = 5
TEXT_RERANK_AVOID_PENALTY = 3

CHEAPER_BUDGET_FALLBACK_MAX = 100.0
CHEAPER_BUDGET_RATIO = 0.8
CHEAPER_BUDGET_MIN_MAX = 50.0

LEGACY_MAIN_CHUNK_MAX_CHARS = 400
LEGACY_SUB_CHUNK_MAX_CHARS = 200
LEGACY_HEADER_MAX_CHARS = 50
SEMANTIC_CHUNK_MAX_CHARS = 480
MARKETING_CHUNK_MAX_CHARS = 420
SUMMARY_SENTENCE_MAX_CHARS = 160
ALIAS_MAX_COUNT = 10
DEDUP_VALUE_MAX_CHARS = 80
